# Generated by Django 4.0.4 on 2022-05-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='restaurant/event')),
                ('price', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='restaurant/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='restaurant/menu')),
                ('price', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userName', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password1', models.CharField(max_length=250)),
                ('password2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Armenia', 'Armenia'), ('Buenavista', 'Buenavista'), ('Calarcá', 'Calarcá'), ('Circasia', 'Circasia'), ('Córdoba', 'Córdoba'), ('Filandia', 'Filandia'), ('Génova', 'Génova'), ('Montenegro', 'Montenegro'), ('Pijao', 'Pijao'), ('Salento', 'Salento')], default='Armenia', max_length=20)),
                ('departamento', models.CharField(default='Quindío', max_length=20)),
                ('price_min', models.CharField(max_length=10)),
                ('price_max', models.CharField(max_length=50)),
                ('parking', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('credit_card', models.BooleanField()),
                ('debit_card', models.BooleanField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Buffet', 'Buffet'), ('Comida rápida', 'Comida rápida'), ('Casual', 'Casual'), ('De autor', 'De autor'), ('Gourmet', 'Gourmet'), ('Temático', 'Temático')], default='Gourmet', max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('principal_image', models.ImageField(upload_to='restaurant/principal-img')),
                ('slug', models.SlugField(unique=True)),
                ('events', models.ManyToManyField(to='restaurante.event')),
                ('gallery', models.ManyToManyField(to='restaurante.gallery')),
                ('menu', models.ManyToManyField(to='restaurante.itemmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cell', models.IntegerField()),
                ('customers', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('reservation', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurante.restaurant')),
            ],
        ),
    ]
