# Generated by Django 3.2.13 on 2022-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_restaurant_principal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/principal-img'),
        ),
    ]
