# Generated by Django 3.2.13 on 2022-05-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_restaurant_principal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation',
            field=models.DateTimeField(),
        ),
    ]
